apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: todolist

resources:
  - namespace.yaml
  - mysql-statefulset.yaml
  - backend-deployment.yaml
  - frontend-deployment.yaml
  - ingress.yaml

commonLabels:
  app.kubernetes.io/name: todolist
  app.kubernetes.io/managed-by: argocd

images:
  - name: nuhgnod/todolist-api
    newTag: latest
  - name: nuhgnod/todolist-frontend
    newTag: latest
